# Generated by Django 4.1.3 on 2022-11-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='owner',
            new_name='users',
        ),
    ]
